# Docker Compose
# https://docs.docker.com/compose/

version: '3.6'
services:
  # Python
  app:
    environment: &environment
      - STAGE=dev
    image: equipindustry-terraform-aws-vpc-app-dev
    build:
      args:
        stage: dev

  check:
    image: equipindustry-terraform-aws-vpc-check-dev
    environment: *environment
    build:
      context: .
      dockerfile: provision/docker/check/Dockerfile
      args:
        stage: dev
    volumes:
      - .:/usr/src
    env_file:
      - .env
